CREATE TABLE `import_batch` (
	`id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`tradingAccountId` text NOT NULL,
	`originalFileName` text NOT NULL,
	`fileFormat` text NOT NULL,
	`fileHash` text NOT NULL,
	`fileSize` integer NOT NULL,
	`sourcePlatform` text,
	`platformDetection` text DEFAULT 'UNKNOWN' NOT NULL,
	`sourceKind` text NOT NULL,
	`adapterVersion` text NOT NULL,
	`sourceTimezone` text,
	`sourceTimezoneConfirmed` integer DEFAULT false NOT NULL,
	`pnlMode` text DEFAULT 'UNKNOWN' NOT NULL,
	`feeSignConvention` text DEFAULT 'UNKNOWN' NOT NULL,
	`feesConfirmed` integer DEFAULT false NOT NULL,
	`accountCurrency` text,
	`totalRows` integer DEFAULT 0 NOT NULL,
	`validRows` integer DEFAULT 0 NOT NULL,
	`invalidRows` integer DEFAULT 0 NOT NULL,
	`duplicateRows` integer DEFAULT 0 NOT NULL,
	`insertedRows` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'PROCESSING' NOT NULL,
	`failureCode` text,
	`createdAt` integer NOT NULL,
	`completedAt` integer,
	FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`tradingAccountId`) REFERENCES `trading_account`(`id`) ON UPDATE no action ON DELETE cascade
);
